### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Foryah** [norchard/norchard.github.io#2]
Hey, 

First great article, and second you have two broken links here:

https://github.com/norchard/norchard.github.io/blob/6829fd2a58bb0cc1a68f1bab68f6f7d17ae9af88/blog/what-should-i-work-on.html#L87

It's odd... you are using `a href` but they act la anchors :thinking:

**Comment by norchard** [comment]
Thanks! Fixed those links 👍

**Comment by Foryah** [comment]
Awesome!

One more nitpick: React is technically a library, not a framework ([source](https://develoger.com/is-reactjs-library-or-a-framework-a14786f681a0)). 
https://github.com/norchard/norchard.github.io/blob/6829fd2a58bb0cc1a68f1bab68f6f7d17ae9af88/blog/what-should-i-work-on.html#L90
